name: Deploy to IPFS with Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy all files
      uses: popovoleksandr/ipfs-pinata-deploy-action@v1
      with:
        pinataApiKey: ${{ secrets.PINATA_API_KEY }}
        pinataSecretApiKey: ${{ secrets.PINATA_API_SECRET }}
        pathToUpload: ./

    - name: Deploy partition1 folder
      uses: popovoleksandr/ipfs-pinata-deploy-action@v1
      with:
        pinataApiKey: ${{ secrets.PINATA_API_KEY }}
        pinataSecretApiKey: ${{ secrets.PINATA_API_SECRET }}
        pathToUpload: ./partition1

    - name: Deploy Chaton.jpeg only
      uses: popovoleksandr/ipfs-pinata-deploy-action@v1
      with:
        pinataApiKey: ${{ secrets.PINATA_API_KEY }}
        pinataSecretApiKey: ${{ secrets.PINATA_API_SECRET }}
        pathToUpload: ./Chaton.jpeg
