name: Deploy Website to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install pinata-web3

    - name: Deploy Website to IPFS
      run: |
        node uploadWebsite.js
      env:
        PINATA_JWT: ${{ secrets.PINATA_JWT }}
        PINATA_GATEWAY: ${{ secrets.PINATA_GATEWAY }}
