name: Deploy to IPFS with Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install -g ipfs-deploy

    - name: Deploy to IPFS via Pinata
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
      run: ipfs-deploy -p pinata ./  
