name: Deploy to IPFS with Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install -g ipfs-deploy

    - name: Deploy to IPFS via Pinata
      env:
        PINATA_API_KEY: ${16a894ddda6da177fa99}
        PINATA_API_SECRET: ${b0a7fdd1794a51c2783fbdee1ca80db543068f4a2f464186f15e390f77091327}
      run: ipfs-deploy -p pinata ./  # Déploie tout le contenu du repository
